[package]
name = "system"
version = "0.0.1"
authors = ["Kingsquee <Kingsquee@users.noreply.github.com>"]

[lib]
name = "system"
path = "src/system.rs"

[dependencies.worldsong_hierarchy]
path = "./../../../../shared/worldsong_hierarchy"

[dependencies]
regex = "*"