[package]
name = "utensils_common"
version = "0.0.1"
authors = ["Kingsquee <Kingsquee@users.noreply.github.com>"]

[lib]
name = "utensils_common"
path = "src/utensils_common.rs"

[dependencies.worldsong_hierarchy]
path = "./../../../../shared/worldsong_hierarchy"

[dependencies]
regex = "*"