[package]

name = "worldsong-kernel"
version = "0.0.1"
authors = ["Kingsley Tolmie <kingsley.tolmie@gmail.com>"]

[[bin]]
name = "kernel"
path = "kernel.rs"

[profile.dev]
opt-level=0
debug=true

[dependencies.worldsong-common]
path = "./../common"

[dependencies]
time = "*"
