[package]

name = "compile_macro"
version = "0.0.1"
authors = ["Kingsley Tolmie <kingsley.tolmie@gmail.com>"]

[[bin]]
name = "compile_macro"
path = "compile_macro.rs"

[dependencies.worldsong-environment]
path = "./../../environment"
