[package]

name = "worldsong-process-graphics"
version = "0.0.1"
authors = ["Kingsley Tolmie <kingsley.tolmie@gmail.com>"]

[lib]
name = "graphics"
path = "graphics.rs"
crate-type = ["dylib"]

[profile.dev]
opt-level=0
debug=true

[dependencies.worldsong-common]
path = "./../../../../common"
