// ATTENTION: This file is automatically generated. Don't modify it unless your life is terrible.
#[macro_use]
extern crate common;
extern crate simulation;
extern crate kernel;
extern crate graphics;


pub use simulation::SimulationState;
pub use kernel::KernelState;
pub use graphics::GraphicsState;


data! {
    Data {
       simulation: SimulationState = SimulationState::new()
       kernel: KernelState = KernelState::new()
       graphics: GraphicsState = GraphicsState::new()
    }
}
