[package]

name = "compile_schedule"
version = "0.0.1"
authors = ["Kingsley Tolmie <kingsley.tolmie@gmail.com>"]

[[bin]]
name = "compile_schedule"
path = "compile_schedule.rs"

[dependencies.worldsong-environment]
path = "./../../environment"
