[package]

name = "worldsong-common"
version = "0.0.1"
authors = ["Kingsley Tolmie <kingsley.tolmie@gmail.com>"]

[lib]
name = "common"
path = "common.rs"
crate-type = ["dylib", "rlib"]
plugin = true

[dependencies.lazy_static]
