[package]
name = "kernel"
version = "0.0.1"
authors = [ "the ghost in the machine" ]

[lib]
name = "kernel"
path = "kernel_state.rs"
crate_type = ["dylib"]
plugin = true

# Required by all worldsong submodules
[dependencies.worldsong-common]
path = "/home/kingsley/Projects/rust/Worldsong/common"
