[package]
name = "worldsong_config"
version = "0.1.0"
authors = ["Kingsquee <Kingsquee@users.noreply.github.com>"]

[lib]
name = "worldsong_config"
path = "src/worldsong_config.rs"
crate-type = ["dylib", "rlib"]
plugin = true